# This file is auto-generated from nearly_equal.jmd.
# Do not edit this file manually.

module NearlyEqual

"""
    isNearlyEqual(a, b; tolerance=1e-6)

    Check if `a` and `b` are nearly equal. The default tolerance is `1e-6`.
"""
@inline function isNearlyEqual(
    a::T,
    b::T;
    tolerance=1e-6
)::Bool where {T <: Real}
    if tolerance < 0
        throw(ArgumentError("tolerance must be non-negative"))
    end

    return abs(a - b) < tolerance
end

export isNearlyEqual

end
