# This file is auto-generated from interval_pcm.jmd.
# Do not edit this file manually.

module IntervalPCM

using IntervalArithmetic
using IntervalArithmetic.Symbols

include("../../nearly_equal/v1/nearly_equal.jl")
using .NearlyEqual

include("../../interval_weight_vector/v1/interval_weight_vector.jl")
using .IntervalWeightVector

"""
    isIntervalPCM(A; allow_uncommon=false)

Check whether the given matrix `A` is an interval PCM.
"""
@inline function isIntervalPCM(
    A::Matrix{Interval{T}};
    allow_uncommon::Bool = false
)::Bool where {T <: Real}
    m, n = size(A)
    # Check if the matrix is square
    if m != n return false end

    for i = 1:n
        for j in (i+1):n
            if !iscommon(A[i,j])
                # non-common interval means like: ∅, (-∞, 1]
                if allow_uncommon
                    continue
                else
                    return false
                end
            end
            
            aᵢⱼᴸ = inf(A[i,j]); aᵢⱼᵁ = sup(A[i,j])
            aⱼᵢᴸ = inf(A[j,i]); aⱼᵢᵁ = sup(A[j,i])

            # Check if the lower bound is positive
            if aᵢⱼᴸ ≤ 0 || aⱼᵢᴸ ≤ 0 return false end

            # Check reciprocity
            if !isNearlyEqual(aᵢⱼᴸ, 1 / aⱼᵢᵁ) return false end
            if !isNearlyEqual(aᵢⱼᵁ, 1 / aⱼᵢᴸ) return false end
        end
    end

    # Check if the diagonal elements are [1, 1]
    for i in 1:n
        aᵢⱼᴸ = inf(A[i,i]); aᵢⱼᵁ = sup(A[i,i])
        if !isNearlyEqual(aᵢⱼᴸ, 1.0, tolerance=1e-10) return false end
        if !isNearlyEqual(aᵢⱼᵁ, 1.0, tolerance=1e-10) return false end
    end

    return true 
end

"""
    PCM(W)

Generate an interval PCM from the interval weight vector `W`.
Throws an `ArgumentError` if `W` is not an interval weight vector.
"""
function PCM(
    W::Vector{Interval{T}}
)::Matrix{Interval{T}} where {T <: Real}
    if !isIntervalWeightVector(W)
        throw(ArgumentError("The given vector is not an interval weight vector."))
    end

    n = length(W)
    A = Matrix{Interval{T}}(undef, n, n)
    
    for i = 1:n, j = 1:n
        if i == j
            A[i,j] = 1.0..1.0
            continue
        end

        Wᵢ = W[i]; Wⱼ = W[j]
        wᵢᴸ = inf(Wᵢ); wᵢᵁ = sup(Wᵢ)
        wⱼᴸ = inf(Wⱼ); wⱼᵁ = sup(Wⱼ)

        aᵢⱼᴸ = wᵢᴸ / wⱼᵁ; aᵢⱼᵁ = wᵢᵁ / wⱼᴸ
        A[i,j] = aᵢⱼᴸ..aᵢⱼᵁ
    end

    return A
end

export isIntervalPCM, PCM

end
