version: '3'
services:
  devcontainer:
    image: jupyter/datascience-notebook:julia-1.9.3
    volumes:
      - ../:/workspace
    command: sleep infinity
    environment:
      - MONGO_URI=mongodb://mongo:27017
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ../mongo-data:/data/db

volumes:
  mongo-data:
